apiVersion: v1
clusters:
- cluster:
    server: http://example.com
  name: example
contexts:
- context:
    cluster: example
    user: test
  name: test
current-context: test
kind: Config
preferences: {}
users:
- name: test
  user:
    token: xxxxx
